apiVersion: v1
kind: PersistentVolume
metadata:
  name: pricelist-db-pv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    pricelist-storage: "yes"
spec:
  iscsi:
    targetPortal: 192.168.203.101:3260
    iqn: iqn.2004-04.com.qnap:ts-932x:iscsi.ocp.28d738
    lun: 0
    fsType: 'ext4'
    readOnly: false
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: pricelist-db-pvc
    namespace: pricelist