apiVersion: v1
kind: PersistentVolume
metadata:
  name: pricelist-db-pv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    pricelist-storage: "yes"
spec:
  nfs:
   path: /ocp-examples
   server: 192.168.203.101
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: pricelist-db-pvc
    namespace: pricelist